/*amd /ex/TabControl.xml 2827 b520942cc18ab70ed8a2f83f443ee0573aa37cbe2c0db00372da98b647b76c64 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function() {
	
};

scwin.trigger1_onclick = function(e) {
    if(t1.tabArr[0].disabled == false){
        t1.disableTab(0);
    } else{
        t1.enableTab(0);
    }
};

}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'w2:tabControl',A:{id:'t1',alwaysDraw:'false',style:'width: 500px;height: 200px;',tabScroll:'true',changeActiveTab:'true',keepDisabledTab:'true',tabScrollAuto:'true'},E:[{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px;',id:'tabs1',label:'tab1'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs2',label:'tab2'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs3',label:'tab3'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs4',label:'tab4'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs5',label:'tab5'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs6',label:'tab6'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs7',label:'tab7'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs8',label:'tab8'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px',id:'tabs9',label:'tab9'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content1'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content2'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content3'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content4'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content5'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content6'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content7'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content8'}},{T:1,N:'w2:content',A:{alwaysDraw:'false',style:'height:170px',id:'content9'}}]},{T:1,N:'xf:trigger',A:{type:'button',id:'trigger1',style:'position:absolute;top:204px;left:5px;width:125px;height:35px;','ev:onclick':'scwin.trigger1_onclick'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'ableTab()'}]}]}]}]}]})