/*amd /ex/treeView.xml 3146 236022e1ae5a1fe46be2ce5d670d0eb42c2cd1909bdb0687a2229fa34e6dff75 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dataList1',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'col1',name:'name1',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col2',name:'name2',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col3',name:'name3',dataType:'text'}}]},{T:1,N:'w2:data',A:{use:'true'},E:[{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'a'}]},{T:1,N:'col2',E:[{T:4,cdata:'1'}]},{T:1,N:'col3',E:[{T:4,cdata:'con'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'k'}]},{T:1,N:'col2',E:[{T:4,cdata:'2'}]},{T:1,N:'col3',E:[{T:4,cdata:'nat'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'s'}]},{T:1,N:'col2',E:[{T:4,cdata:'3'}]},{T:1,N:'col3',E:[{T:4,cdata:'ct'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'b'}]},{T:1,N:'col2',E:[{T:4,cdata:'3'}]},{T:1,N:'col3',E:[{T:4,cdata:'ct'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'c'}]},{T:1,N:'col2',E:[{T:4,cdata:'2'}]},{T:1,N:'col3',E:[{T:4,cdata:'nat'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'B'}]},{T:1,N:'col2',E:[{T:4,cdata:'3'}]},{T:1,N:'col3',E:[{T:4,cdata:'ct'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'e'}]},{T:1,N:'col2',E:[{T:4,cdata:'1'}]},{T:1,N:'col3',E:[{T:4,cdata:'con'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'g'}]},{T:1,N:'col2',E:[{T:4,cdata:'2'}]},{T:1,N:'col3',E:[{T:4,cdata:'nat'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Be'}]},{T:1,N:'col2',E:[{T:4,cdata:'3'}]},{T:1,N:'col3',E:[{T:4,cdata:'ct'}]}]}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function() {
	
};

scwin.trigger1_onclick = function(e) {
    t1.spanAll(false);
};

}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'w2:treeview',A:{id:'t1',dataType:'listed',tooltipGroupClass:'false',style:'position:absolute; top:77px; left:61px; width:260px; height:267px; ',showCheckbox:'true',hierarchy:'true'},E:[{T:1,N:'w2:itemset',A:{nodeset:'data:dataList1'},E:[{T:1,N:'w2:label',A:{ref:'col1'}},{T:1,N:'w2:value',A:{ref:'col3'}},{T:1,N:'w2:depth',A:{ref:'col2'}},{T:1,N:'w2:folder',A:{ref:''}},{T:1,N:'w2:checkbox',A:{ref:''}},{T:1,N:'w2:checkboxDisabled',A:{ref:''}},{T:1,N:'w2:image',A:{ref:''}},{T:1,N:'w2:iconImage',A:{ref:''}},{T:1,N:'w2:selectedImage',A:{ref:''}},{T:1,N:'w2:expandedImage',A:{ref:''}},{T:1,N:'w2:leafImage',A:{ref:''}}]}]},{T:1,N:'xf:trigger',A:{type:'button',id:'trigger1',style:'position:absolute; top:86px; left:391px; width:152px; height:38px; ','ev:onclick':'scwin.trigger1_onclick'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'spanAll'}]}]}]}]}]})